// Code generated by "stringer --type=TagId"; DO NOT EDIT.

package nbt

import "fmt"

const (
	_TagId_name_0 = "Tag_ENDTag_ByteTag_ShortTag_IntTag_LongTag_Float"
	_TagId_name_1 = "Tag_StringTag_ListTag_Compound"
)

var (
	_TagId_index_0 = [...]uint8{0, 7, 15, 24, 31, 39, 48}
	_TagId_index_1 = [...]uint8{0, 10, 18, 30}
)

func (i TagId) String() string {
	switch {
	case 0 <= i && i <= 5:
		return _TagId_name_0[_TagId_index_0[i]:_TagId_index_0[i+1]]
	case 8 <= i && i <= 10:
		i -= 8
		return _TagId_name_1[_TagId_index_1[i]:_TagId_index_1[i+1]]
	default:
		return fmt.Sprintf("TagId(%d)", i)
	}
}
