// Code generated by "stringer --type=TagType"; DO NOT EDIT.

package nbt

import "fmt"

const (
	_TagType_name_0 = "Tag_ENDTag_ByteTag_ShortTag_IntTag_LongTag_Float"
	_TagType_name_1 = "Tag_StringTag_ListTag_Compound"
)

var (
	_TagType_index_0 = [...]uint8{0, 7, 15, 24, 31, 39, 48}
	_TagType_index_1 = [...]uint8{0, 10, 18, 30}
)

func (i TagType) String() string {
	switch {
	case 0 <= i && i <= 5:
		return _TagType_name_0[_TagType_index_0[i]:_TagType_index_0[i+1]]
	case 8 <= i && i <= 10:
		i -= 8
		return _TagType_name_1[_TagType_index_1[i]:_TagType_index_1[i+1]]
	default:
		return fmt.Sprintf("TagType(%d)", i)
	}
}
